[package]
name = "flipper_backups"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
clokwerk = "0.4.0"
dotenvy = "0.15.7"
postgres = "0.19.10"
reqwest = { version = "0.12.22", features = ["blocking", "json"] }
serde = { version = "1.0.219", features = ["derive"] }
